version: '3'

services:

#  exchange_rater_app: &exchange_rater_app
#    build:
#      context: .
#      dockerfile: ./compose/local/django/Dockerfile
#    hostname: exchange_rater_app
#    image: exchange_rater_app
#    container_name: exchange_rater_app
#    depends_on:
#      - exchange_rater_postgres
#    volumes:
#      - .:/app:z
#    env_file:
#      - .env
#    ports:
#      - "8000:8000"
#    command: /start

  exchange_rater_rpostgres:
    hostname: exchange_rater_rpostgres
    container_name: exchange_rater_postgres
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: exchange_rater_postgres
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
      - ${POSTGRES_BACKUPS}:/backups
    env_file:
      - .env
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"

